//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_asociados
    {
        public int AsociadoId { get; set; }
        public Nullable<int> SocioId { get; set; }
        public Nullable<int> CupoId { get; set; }
        public Nullable<System.DateTime> FechaAsoc { get; set; }
        public string Estado { get; set; }
    
        public virtual fc_clientesentidad fc_clientesentidad { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }
    }
}
