//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_clientesentidad
    {
        public fc_clientesentidad()
        {
            this.fc_asociados = new HashSet<fc_asociados>();
            this.fc_transacciones = new HashSet<fc_transacciones>();
        }
    
        public int EntidadId { get; set; }
        public int ClientesId { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<decimal> ValorCupo { get; set; }
        public Nullable<decimal> TotalPrestado { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Estado { get; set; }
        public int CupoId { get; set; }
    
        public virtual ICollection<fc_asociados> fc_asociados { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }
        public virtual ICollection<fc_transacciones> fc_transacciones { get; set; }
        public virtual fc_entidad fc_entidad { get; set; }
    }
}
