//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_entidad
    {
        public fc_entidad()
        {
            this.fc_clientesentidad = new HashSet<fc_clientesentidad>();
        }
    
        public int TercerosId { get; set; }
        public Nullable<System.DateTime> FechaMat { get; set; }
        public Nullable<decimal> ValorMat { get; set; }
        public Nullable<decimal> ValorMes { get; set; }
        public string Estado { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<fc_clientesentidad> fc_clientesentidad { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }
    }
}
