//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_transacciones
    {
        public int TransaccionesId { get; set; }
        public Nullable<int> CupoId { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaTrans { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Credito { get; set; }
    
        public virtual fc_clientesentidad fc_clientesentidad { get; set; }
    }
}
