//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_terceros
    {
        public fc_terceros()
        {
            this.fc_clientesentidad = new HashSet<fc_clientesentidad>();
        }
    
        public int terceroId { get; set; }
        public string tipodoc { get; set; }
        public string tipoper { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
    
        public virtual fc_asociados fc_asociados { get; set; }
        public virtual ICollection<fc_clientesentidad> fc_clientesentidad { get; set; }
        public virtual fc_entidad fc_entidad { get; set; }
    }
}
