//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_menu
    {
        public string fc_menuid { get; set; }
        public string fc_titulo { get; set; }
        public string fc_descripcion { get; set; }
        public string fc_padreid { get; set; }
        public Nullable<int> fc_posicion { get; set; }
        public string fc_icono { get; set; }
        public Nullable<int> fc_habilitado { get; set; }
        public string fc_url { get; set; }
        public string fc_modulo { get; set; }
        public string fc_target { get; set; }
        public string fc_ppal { get; set; }
        public string fc_roles { get; set; }
    }
}
