//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_menu
    {
        public string fc_menuid { get; set; }
        public string fc_titulo { get; set; }
        public string fc_descripcion { get; set; }
        public string fc_padreid { get; set; }
        public Nullable<int> fc_posicion { get; set; }
        public string fc_icono { get; set; }
        public Nullable<int> fc_habilitado { get; set; }
        public string fc_url { get; set; }
        public string fc_modulo { get; set; }
        public string fc_target { get; set; }
        public string fc_ppal { get; set; }
        public string fc_roles { get; set; }
    }
}
