//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gdocumentos
    {
        public int idGDocumentos { get; set; }
        public string nombre { get; set; }
        public Nullable<int> longitud { get; set; }
        public string tipo { get; set; }
        public string estado { get; set; }
    
        public virtual gddocumentos gddocumentos { get; set; }
    }
}
