//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finanzacloudEntities : DbContext
    {
        public finanzacloudEntities()
            : base("name=finanzacloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<fc_asociadoscupo> fc_asociadoscupo { get; set; }
        public DbSet<fc_clientesentidad> fc_clientesentidad { get; set; }
        public DbSet<fc_entidad> fc_entidad { get; set; }
        public DbSet<fc_terceros> fc_terceros { get; set; }
        public DbSet<fc_transacciones> fc_transacciones { get; set; }
        public DbSet<fc_asociados> fc_asociados { get; set; }
    }
}
