//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_profiles
    {
        public int userId { get; set; }
        public string valueindex { get; set; }
        public string stringdata { get; set; }
        public byte[] binarydata { get; set; }
        public System.DateTime lastUpdatedDate { get; set; }
    }
}
