//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_users
    {
        public int id { get; set; }
        public int applicationId { get; set; }
        public string name { get; set; }
        public bool isAnonymous { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
    }
}
