//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_sessioncleanup
    {
        public System.DateTime LastRun { get; set; }
        public int IntervalMinutes { get; set; }
        public int ApplicationId { get; set; }
    }
}
