//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class series
    {
        public series()
        {
            this.subseries = new HashSet<subseries>();
        }
    
        public string idSerie { get; set; }
        public string Serie { get; set; }
        public string Procedimiento { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<subseries> subseries { get; set; }
    }
}
