//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class series
    {
        public series()
        {
            this.subseries = new HashSet<subseries>();
        }
    
        public string idSerie { get; set; }
        public string Serie { get; set; }
        public string Procedimiento { get; set; }
    
        public virtual ICollection<subseries> subseries { get; set; }
    }
}
