//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subseries
    {
        public subseries()
        {
            this.unidaddocumental = new HashSet<unidaddocumental>();
            this.tiposdocumentales = new HashSet<tiposdocumentales>();
        }
    
        public string idSubSeries { get; set; }
        public string SubSerie { get; set; }
        public Nullable<int> RetencionAG { get; set; }
        public Nullable<int> DisposicionA { get; set; }
        public Nullable<bool> DisposicionCT { get; set; }
        public Nullable<bool> DisposicionE { get; set; }
        public Nullable<bool> DisposicionMD { get; set; }
        public Nullable<bool> DisposicionS { get; set; }
        public string Series_idSerie { get; set; }
        public string Estado { get; set; }
    
        public virtual series series { get; set; }
        public virtual ICollection<unidaddocumental> unidaddocumental { get; set; }
        public virtual ICollection<tiposdocumentales> tiposdocumentales { get; set; }
    }
}
