//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subseries
    {
        public subseries()
        {
            this.tiposdocumentales = new HashSet<tiposdocumentales>();
            this.unidaddocumental = new HashSet<unidaddocumental>();
        }
    
        public string idSubSeries { get; set; }
        public string SubSerie { get; set; }
        public Nullable<int> RetencionAG { get; set; }
        public Nullable<int> DisposicionA { get; set; }
        public Nullable<bool> DisposicionCT { get; set; }
        public Nullable<bool> DisposicionE { get; set; }
        public Nullable<bool> DisposicionMD { get; set; }
        public Nullable<bool> DisposicionS { get; set; }
        public string Series_idSerie { get; set; }
        public string Estado { get; set; }
    
        public virtual series series { get; set; }
        public virtual ICollection<tiposdocumentales> tiposdocumentales { get; set; }
        public virtual ICollection<unidaddocumental> unidaddocumental { get; set; }
    }
}
