//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class terceros_dep
    {
        public string IdTerceros { get; set; }
        public string IdDependencias { get; set; }
        public string Estado { get; set; }
    
        public virtual dependencias dependencias { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }
    }
}
