//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposdocumentales
    {
        public string idTipDocumentales { get; set; }
        public string Nombe { get; set; }
        public string TD_Original { get; set; }
        public string TD_Copia { get; set; }
        public string SerieId { get; set; }
    
        public virtual subseries subseries { get; set; }
    }
}
