//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposdocumentales
    {
        public tiposdocumentales()
        {
            this.unidadd_tipodoc = new HashSet<unidadd_tipodoc>();
        }
    
        public string idTipDocumentales { get; set; }
        public string Nombe { get; set; }
        public string TD_Original { get; set; }
        public string TD_Copia { get; set; }
        public string SubSerieId { get; set; }
        public string Estado { get; set; }
    
        public virtual subseries subseries { get; set; }
        public virtual ICollection<unidadd_tipodoc> unidadd_tipodoc { get; set; }
    }
}
