//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposdocumentales
    {
        public tiposdocumentales()
        {
            this.unidadd_tipodoc = new HashSet<unidadd_tipodoc>();
        }
    
        public string idTipDocumentales { get; set; }
        public string Nombe { get; set; }
        public string TD_Original { get; set; }
        public string TD_Copia { get; set; }
        public string SubSerieId { get; set; }
        public string Estado { get; set; }
    
        public virtual subseries subseries { get; set; }
        public virtual ICollection<unidadd_tipodoc> unidadd_tipodoc { get; set; }
    }
}
