//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidadd_tipodoc
    {
        public string IdUnidadDoc { get; set; }
        public string IdTipoDoc { get; set; }
        public string Codigo { get; set; }
        public string FechaDoc { get; set; }
        public string PagIni { get; set; }
        public string CantidadPag { get; set; }
        public string Descripcion { get; set; }
    
        public virtual unidaddocumental unidaddocumental { get; set; }
        public virtual tiposdocumentales tiposdocumentales { get; set; }
    }
}
