//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidadd_tipodoc
    {
        public string IdUnidadDoc { get; set; }
        public string IdTipoDoc { get; set; }
        public string Codigo { get; set; }
        public string FechaDoc { get; set; }
        public string PagIni { get; set; }
        public string CantidadPag { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual unidaddocumental unidaddocumental { get; set; }
        public virtual tiposdocumentales tiposdocumentales { get; set; }
    }
}
