//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_asociadosDto
    {
        public int AsociadoId { get; set; }
        public string SocioId { get; set; }
        public Nullable<int> CupoId { get; set; }
        public Nullable<System.DateTime> FechaAsoc { get; set; }
        public string Estado { get; set; }
    
      /*  public virtual fc_clientesentidad fc_clientesentidad { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }
       * */
    }
}
