//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_clientesentidadDto
    {
        public fc_clientesentidadDto()
        {
        /*    this.fc_transacciones = new HashSet<fc_transacciones>();
            this.fc_asociados = new HashSet<fc_asociados>();*/
        }

        public string EntidadId { get; set; }
        public string ClientesId { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<decimal> ValorCupo { get; set; }
        public Nullable<decimal> TotalPrestado { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Estado { get; set; }
        public int CupoId { get; set; }
    
        /*
        public virtual ICollection<fc_transacciones> fc_transacciones { get; set; }
        public virtual fc_entidad fc_entidad { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }
        public virtual ICollection<fc_asociados> fc_asociados { get; set; }*/
    }
}
