//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_entidadDto
    {
        public fc_entidadDto()
        {
          //  this.fc_clientesentidad = new HashSet<fc_clientesentidad>();
        }

        public string TercerosId { get; set; }
        public Nullable<System.DateTime> FechaMat { get; set; }
        public Nullable<decimal> ValorMat { get; set; }
        public Nullable<decimal> ValorMes { get; set; }
        public string Estado { get; set; }
        public byte[] Logo { get; set; }
    
        /*public virtual ICollection<fc_clientesentidad> fc_clientesentidad { get; set; }
        public virtual fc_terceros fc_terceros { get; set; }*/
    }
}
