//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class fc_tercerosDto
    {
        public fc_tercerosDto()
        {
        //    this.fc_asociadoscupo = new HashSet<fc_asociadoscupo>();
         //   this.fc_clientesentidad = new HashSet<fc_clientesentidad>();
        }

        public string terceroId { get; set; }
        public string tipodoc { get; set; }
        public string tipoper { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string lugarexpe { get; set; }
    
     /*   public virtual ICollection<fc_asociadoscupo> fc_asociadoscupo { get; set; }
        public virtual ICollection<fc_clientesentidad> fc_clientesentidad { get; set; }
        public virtual fc_entidad fc_entidad { get; set; }
        public virtual fc_asociados fc_asociados { get; set; }*/
    }
}
